# Data Cleaning and Preparation

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('SnapDeal.csv')

In [ ]:
df.head()

,Timestamp,age,Gender,Purchase_Frequency,Purchase_Categories,Personalized_Recommendation_Frequency,Browsing_Frequency,Product_Search_Method,Search_Result_Exploration,Customer_Reviews_Importance,...,Review_Left,Review_Reliability,Review_Helpfulness,Personalized_Recommendation_Frequency,Recommendation_Helpfulness,Rating_Accuracy,Shopping_Satisfaction,Service_Appreciation,Improvement_Areas,transaction
0,2023/06/07 11:06:40 PM GMT+5:30,59,Others,Once a week,Beauty and Personal Care,Yes,Few times a month,others,Multiple pages,4,...,Yes,Rarely,No,1,Yes,3,3,Customer service,User interface of app,433348
1,2023/06/06 7:08:47 PM GMT+5:30,48,Female,Once a month,Beauty and Personal Care;Clothing and Fashion;...,Sometimes,Rarely,categories,Multiple pages,1,...,No,Never,Sometimes,1,No,5,2,.,.,735054
2,2023/06/08 9:39:30 PM GMT+5:30,57,Prefer not to say,Multiple times a week,Groceries and Gourmet Food,Sometimes,Rarely,Keyword,First page,2,...,Yes,Rarely,No,5,Sometimes,3,3,Customer service,Product quality and accuracy,119350
3,2023/06/07 9:22:24 PM GMT+5:30,30,Others,Few times a month,Groceries and Gourmet Food;Beauty and Personal...,No,Few times a month,others,Multiple pages,2,...,Yes,Rarely,Sometimes,4,Sometimes,4,5,Customer service,.,180686
4,2023/06/06 7:21:26 PM GMT+5:30,51,Female,Once a month,Groceries and Gourmet Food;Beauty and Personal...,No,Few times a month,Filter,First page,5,...,Yes,Moderately,Sometimes,1,Yes,3,1,.,I don't have any problem with Amazon,538184

In [ ]:
df.shape

(800, 24)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 24 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Timestamp                               800 non-null    object
 1   age                                     800 non-null    int64
 2   Gender                                  800 non-null    object
 3   Purchase_Frequency                      800 non-null    object
 4   Purchase_Categories                     800 non-null    object
 5   Personalized_Recommendation_Frequency   800 non-null    object
 6   Browsing_Frequency                      800 non-null    object
 7   Product_Search_Method                   651 non-null    object
 8   Search_Result_Exploration               800 non-null    object
 9   Customer_Reviews_Importance             800 non-null    int64
 10  Add_to_Cart_Browsing                    800 non-null    object
 11  Cart_Completion_Frequency               800 non-null    object
 12  Cart_Abandonment_Factors                800 non-null    object
 13  Saveforlater_Frequency                  800 non-null    object
 14  Review_Left                             800 non-null    object
 15  Review_Reliability                      800 non-null    object
 16  Review_Helpfulness                      800 non-null    object
 17  Personalized_Recommendation_Frequency   800 non-null    int64
 18  Recommendation_Helpfulness              800 non-null    object
 19  Rating_Accuracy                         800 non-null    int64
 20  Shopping_Satisfaction                   800 non-null    int64
 21  Service_Appreciation                    800 non-null    object
 22  Improvement_Areas                       800 non-null    object
 23  transaction                             800 non-null    int64
dtypes: int64(6), object(18)
memory usage: 150.1+ KB

## No Duplicates Found

In [ ]:
df.duplicated().sum()

np.int64(0)

## Standardizing categorical / numerical entries

In [ ]:
non_numeric_cols = df.select_dtypes(include=['object']).columns.to_list()

In [ ]:
# Removing extra spaces from non numeric columns
for col in non_numeric_cols:
    df[col] = df[col].str.strip()

In [ ]:
df['Gender'].unique()

array(['Others', 'Female', 'Prefer not to say', 'Male'], dtype=object)

In [ ]:
df['Purchase_Frequency'].unique()

array(['Once a week', 'Once a month', 'Multiple times a week',
       'Few times a month', 'Less than once a month'], dtype=object)

In [ ]:
df['Personalized_Recommendation_Frequency '].unique()

array([1, 5, 4, 3, 2])

In [ ]:
df['Personalized_Recommendation_Frequency'].unique()

array(['Yes', 'Sometimes', 'No'], dtype=object)

In [ ]:
df['Recommendation_Helpfulness'].unique()

array(['Yes', 'No', 'Sometimes'], dtype=object)

In [ ]:
# Removing duplicate column
df.drop(columns=['Personalized_Recommendation_Frequency'], inplace=True)

In [ ]:
# Missing Values
df.isna().sum()

Timestamp                                   0
age                                         0
Gender                                      0
Purchase_Frequency                          0
Purchase_Categories                         0
Browsing_Frequency                          0
Product_Search_Method                     149
Search_Result_Exploration                   0
Customer_Reviews_Importance                 0
Add_to_Cart_Browsing                        0
Cart_Completion_Frequency                   0
Cart_Abandonment_Factors                    0
Saveforlater_Frequency                      0
Review_Left                                 0
Review_Reliability                          0
Review_Helpfulness                          0
Personalized_Recommendation_Frequency       0
Recommendation_Helpfulness                  0
Rating_Accuracy                             0
Shopping_Satisfaction                       0
Service_Appreciation                        0
Improvement_Areas                           0
transaction                                 0
dtype: int64

In [ ]:
# Column Product_Search_Method has some null values
df['Product_Search_Method'].unique()

array(['others', 'categories', 'Keyword', 'Filter', nan], dtype=object)

In [ ]:
df['Product_Search_Method'].value_counts()

Product_Search_Method
others        182
Keyword       163
categories    156
Filter        150
Name: count, dtype: int64

In [ ]:
# New category added as Unknown Search Method
df['Product_Search_Method'].fillna('Unknown', inplace=True)

/tmp/ipykernel_2675/3727337012.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Product_Search_Method'].fillna('Unknown', inplace=True)

In [ ]:
df['Product_Search_Method'].unique()

array(['others', 'categories', 'Keyword', 'Filter', 'Unknown'],
      dtype=object)

In [ ]:
# Fixing Col Names
df.columns = df.columns.str.strip()

In [ ]:
df.columns

Index(['Timestamp', 'age', 'Gender', 'Purchase_Frequency',
       'Purchase_Categories', 'Browsing_Frequency', 'Product_Search_Method',
       'Search_Result_Exploration', 'Customer_Reviews_Importance',
       'Add_to_Cart_Browsing', 'Cart_Completion_Frequency',
       'Cart_Abandonment_Factors', 'Saveforlater_Frequency', 'Review_Left',
       'Review_Reliability', 'Review_Helpfulness',
       'Personalized_Recommendation_Frequency', 'Recommendation_Helpfulness',
       'Rating_Accuracy', 'Shopping_Satisfaction', 'Service_Appreciation',
       'Improvement_Areas', 'transaction'],
      dtype='object')

In [ ]:
# All numeric cols have correct data type
df['Customer_Reviews_Importance'].dtype

dtype('int64')

In [ ]:
df['Shopping_Satisfaction'].dtype

dtype('int64')

In [ ]:
df['Rating_Accuracy'].dtype

dtype('int64')

In [ ]:
df['age'].dtype

dtype('int64')

In [ ]:
df.to_csv('cleaned_data.csv')